// This file has been auto-generated by <envi_research_github_repository>/scripts/evaluator.py. Please do not modify but instead use the script to regenerate.

#ifndef MAP_itelex_H
#define MAP_itelex_H

#include <string>
#include <unordered_map>
#include <utility>

// map: prefix -> (english probability, vietnamese probability)
extern std::unordered_map<std::string, std::pair<double,double>> map_itelex;

#endif
